name: Linting

# Controls when the action will run.
on:
  workflow_call:

jobs:
  lint-repository:
    name: "Lint repository"
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup env.
        run: |
          sudo apt-get update
          sudo apt-get install -yq bc python3-dev python3-pip python3-tk
          pip install pylint

      - name: Lint repository
        run: |
          pylint -d E1101,duplicate-code pynektools | tee lint.txt

      - name: Check the score
        run: |
          string_score=$(tail -2 lint.txt | head -1)
          score=$( expr ${string_score:28:4})
          min_score=7.00

          echo "Current score: $score"

          if (( $(echo "$score < $min_score" | bc -l) )); then
            echo "Linting requirement not met"
            echo "$score < $min_score"
            exit 1
          fi

      - name: Archive linter report
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: lint.txt
          retention-days: 5
