name: Documentation

# Controls when the action will run.
on:
  workflow_dispatch:

jobs:

  Build_docs:
    name: Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup enviroment
        run: |
          sudo apt-get update
          sudo apt install pandoc -y
          
      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Upgrade pip
        run:  python -m pip install -U pip
          
      - name: Install packages
        env:
          MPICC : $(which mpicc)
        run: |
          pip install mpi4py --no-cache-dir
          pip install numpy
          pip install scipy
          pip install pymech
          pip install tdqm
          pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install pytest
          pip install pytest-json-report
          pip install -U sphinx
          pip install numpydoc
          pip install sphinx_rtd_theme
          pip install jupyter
          pip install pandoc
          pip install nbsphinx
          pip install .

      - name: Build docs
        run: |
          cp examples/*/*ipynb doc/_notebooks/
          sphinx-build doc/ docs/
      
      - name: GH Pages Deployment
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/
          allow_empty_commit: false
          keep_files: false
          force_orphan: false
          publish_branch: gh-pages
          destination_dir: docs/
          enable_jekyll: false
